### ISSUE TITLE
Meteor (?) incompatibility

### ISSUE THREAD

**Issue by tajemniktv** [Chailotl/particular#38]
Hi, not sure if it's worth fixing, but there's most likely an incompatibility with Meteor Client mod;
Minecraft 1.21;

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'particular'!
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ExceptionInInitializerError
	at java.base@22.0.2/java.lang.Class.forName0(Native Method)
	at java.base@22.0.2/java.lang.Class.forName(Class.java:529)
	at java.base@22.0.2/java.lang.Class.forName(Class.java:508)
	at app//net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 9 more
Caused by: java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.Modules.get(java.lang.Class)" because the return value of "meteordevelopment.meteorclient.systems.modules.Modules.get()" is null
	at MC//net.minecraft.world.biome.FoliageColors.getModifiedColor(FoliageColors.java:536)
	at MC//net.minecraft.world.biome.FoliageColors.modifyReturnValue$idb000$meteor-client$onGetBirchColor(FoliageColors.java:521)
	at MC//net.minecraft.world.biome.FoliageColors.getBirchColor(FoliageColors.java:26)
	at com.chailotl.particular.Main.<clinit>(Main.java:52)
	... 16 more
```

Full logs, along with modlist, specs, java (ver, args): https://mclo.gs/HJtt6ZA

**Comment by vitphire** [comment]
Can confirm, the incompatibility is with Meteor, however, the issue is with Meteor, specifically this line in `meteordevelopment/meteorclient/mixin/FoliageColorsMixin.java` : 
```java
Ambience ambience = Modules.get().get(Ambience.class);
```
The issue is caused by `onGetBirchColor` (and `onGetSpruceColor`) getting called (by Particular) earlier than Meteor expects it to be.
Rewriting it to 
```java
Modules modules = Modules.get();
if (modules == null) return original;
Ambience ambience = modules.get(Ambience.class);
```
in both `onGetBirchColor` and `onGetSpruceColor` fixed the issue for me.

This could also likely be solved by initializing `Main::leavesData` in `onInitializeClient` or even later, I don't know.

_(If you don't know how to change and build Meteor for yourself, feel free to [message me on Discord](https://discord.com/users/vitphire))_

**Comment by Big-Iron-Cheems** [comment]
Fixed in Meteor as of [this](https://github.com/MeteorDevelopment/meteor-client/commit/5b1a1537127fb161e6d2886967247bc531eaece2) commit 👍 
Update to our latest dev build.
